package models
// Language : language codes in ISO 639-1 and ISO 3166-1 standards
type Language string

// List of Language
const (
	LANGUAGE_AR Language = "ar"
	LANGUAGE_CA Language = "ca"
	LANGUAGE_ZH_HANS Language = "zh-Hans"
	LANGUAGE_ZH_HANT Language = "zh-Hant"
	LANGUAGE_HR Language = "hr"
	LANGUAGE_CS Language = "cs"
	LANGUAGE_DA Language = "da"
	LANGUAGE_NL Language = "nl"
	LANGUAGE_EN_AU Language = "en-AU"
	LANGUAGE_EN_CA Language = "en-CA"
	LANGUAGE_EN_GB Language = "en-GB"
	LANGUAGE_EN_US Language = "en-US"
	LANGUAGE_FI Language = "fi"
	LANGUAGE_FR Language = "fr"
	LANGUAGE_FR_CA Language = "fr-CA"
	LANGUAGE_DE Language = "de"
	LANGUAGE_EL Language = "el"
	LANGUAGE_HE Language = "he"
	LANGUAGE_HI Language = "hi"
	LANGUAGE_HU Language = "hu"
	LANGUAGE_ID Language = "id"
	LANGUAGE_IT Language = "it"
	LANGUAGE_JA Language = "ja"
	LANGUAGE_KO Language = "ko"
	LANGUAGE_MS Language = "ms"
	LANGUAGE_NO Language = "no"
	LANGUAGE_PL Language = "pl"
	LANGUAGE_PT_BR Language = "pt-BR"
	LANGUAGE_PT_PT Language = "pt-PT"
	LANGUAGE_RO Language = "ro"
	LANGUAGE_RU Language = "ru"
	LANGUAGE_SK Language = "sk"
	LANGUAGE_ES_MX Language = "es-MX"
	LANGUAGE_ES_ES Language = "es-ES"
	LANGUAGE_SV Language = "sv"
	LANGUAGE_TH Language = "th"
	LANGUAGE_TR Language = "tr"
	LANGUAGE_UK Language = "uk"
	LANGUAGE_VI Language = "vi"
)
