package models
// PaywallImageVerticalPositionKind : Paywall image vertical position kind
type PaywallImageVerticalPositionKind string

// List of PaywallImageVerticalPositionKind
const (
	PAYWALLIMAGEVERTICALPOSITIONKIND_HEADER_TITLE PaywallImageVerticalPositionKind = "HeaderTitle"
	PAYWALLIMAGEVERTICALPOSITIONKIND_HEADER_SUBTITLE PaywallImageVerticalPositionKind = "HeaderSubtitle"
	PAYWALLIMAGEVERTICALPOSITIONKIND_HEADER_LIST_TOP PaywallImageVerticalPositionKind = "HeaderListTop"
	PAYWALLIMAGEVERTICALPOSITIONKIND_HEADER_LIST_BOTTOM PaywallImageVerticalPositionKind = "HeaderListBottom"
	PAYWALLIMAGEVERTICALPOSITIONKIND_HEADER_BOTTOM PaywallImageVerticalPositionKind = "HeaderBottom"
	PAYWALLIMAGEVERTICALPOSITIONKIND_HEADER_CENTER PaywallImageVerticalPositionKind = "HeaderCenter"
	PAYWALLIMAGEVERTICALPOSITIONKIND_HEADER_TOP PaywallImageVerticalPositionKind = "HeaderTop"
	PAYWALLIMAGEVERTICALPOSITIONKIND_BODY_BOTTOM PaywallImageVerticalPositionKind = "BodyBottom"
	PAYWALLIMAGEVERTICALPOSITIONKIND_FOOTER_TOP PaywallImageVerticalPositionKind = "FooterTop"
	PAYWALLIMAGEVERTICALPOSITIONKIND_PAYWALL_IMAGE_VERTICAL_POSITION_KIND1 PaywallImageVerticalPositionKind = "PaywallImageVerticalPositionKind1"
	PAYWALLIMAGEVERTICALPOSITIONKIND_PAYWALL_IMAGE_VERTICAL_POSITION_KIND2 PaywallImageVerticalPositionKind = "PaywallImageVerticalPositionKind2"
	PAYWALLIMAGEVERTICALPOSITIONKIND_PAYWALL_IMAGE_VERTICAL_POSITION_KIND3 PaywallImageVerticalPositionKind = "PaywallImageVerticalPositionKind3"
	PAYWALLIMAGEVERTICALPOSITIONKIND_PAYWALL_IMAGE_VERTICAL_POSITION_KIND4 PaywallImageVerticalPositionKind = "PaywallImageVerticalPositionKind4"
	PAYWALLIMAGEVERTICALPOSITIONKIND_PAYWALL_IMAGE_VERTICAL_POSITION_KIND5 PaywallImageVerticalPositionKind = "PaywallImageVerticalPositionKind5"
)
