/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// CustomScreenOutputLabel Custom screen output label, allows user to show this data on mobile
type CustomScreenOutputLabel struct {
	Name string `json:"name"`
	Value BaseText `json:"value"`
}

// NewCustomScreenOutputLabel instantiates a new CustomScreenOutputLabel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomScreenOutputLabel(name string, value BaseText) *CustomScreenOutputLabel {
	this := CustomScreenOutputLabel{}
	this.Name = name
	this.Value = value
	return &this
}

// NewCustomScreenOutputLabelWithDefaults instantiates a new CustomScreenOutputLabel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomScreenOutputLabelWithDefaults() *CustomScreenOutputLabel {
	this := CustomScreenOutputLabel{}
	return &this
}

// GetName returns the Name field value
func (o *CustomScreenOutputLabel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomScreenOutputLabel) GetNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomScreenOutputLabel) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *CustomScreenOutputLabel) GetValue() BaseText {
	if o == nil {
		var ret BaseText
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CustomScreenOutputLabel) GetValueOk() (*BaseText, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CustomScreenOutputLabel) SetValue(v BaseText) {
	o.Value = v
}

func (o CustomScreenOutputLabel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableCustomScreenOutputLabel struct {
	value *CustomScreenOutputLabel
	isSet bool
}

func (v NullableCustomScreenOutputLabel) Get() *CustomScreenOutputLabel {
	return v.value
}

func (v *NullableCustomScreenOutputLabel) Set(val *CustomScreenOutputLabel) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomScreenOutputLabel) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomScreenOutputLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomScreenOutputLabel(val *CustomScreenOutputLabel) *NullableCustomScreenOutputLabel {
	return &NullableCustomScreenOutputLabel{value: val, isSet: true}
}

func (v NullableCustomScreenOutputLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomScreenOutputLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


