/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// BaseDivider Base divider parameters
type BaseDivider struct {
	Kind BaseDividerKind `json:"kind"`
	Styles BaseDividerBlock `json:"styles"`
}

// NewBaseDivider instantiates a new BaseDivider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseDivider(kind BaseDividerKind, styles BaseDividerBlock) *BaseDivider {
	this := BaseDivider{}
	this.Kind = kind
	this.Styles = styles
	return &this
}

// NewBaseDividerWithDefaults instantiates a new BaseDivider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseDividerWithDefaults() *BaseDivider {
	this := BaseDivider{}
	return &this
}

// GetKind returns the Kind field value
func (o *BaseDivider) GetKind() BaseDividerKind {
	if o == nil {
		var ret BaseDividerKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *BaseDivider) GetKindOk() (*BaseDividerKind, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *BaseDivider) SetKind(v BaseDividerKind) {
	o.Kind = v
}

// GetStyles returns the Styles field value
func (o *BaseDivider) GetStyles() BaseDividerBlock {
	if o == nil {
		var ret BaseDividerBlock
		return ret
	}

	return o.Styles
}

// GetStylesOk returns a tuple with the Styles field value
// and a boolean to check if the value has been set.
func (o *BaseDivider) GetStylesOk() (*BaseDividerBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Styles, true
}

// SetStyles sets field value
func (o *BaseDivider) SetStyles(v BaseDividerBlock) {
	o.Styles = v
}

func (o BaseDivider) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["styles"] = o.Styles
	}
	return json.Marshal(toSerialize)
}

type NullableBaseDivider struct {
	value *BaseDivider
	isSet bool
}

func (v NullableBaseDivider) Get() *BaseDivider {
	return v.value
}

func (v *NullableBaseDivider) Set(val *BaseDivider) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseDivider) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseDivider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseDivider(val *BaseDivider) *NullableBaseDivider {
	return &NullableBaseDivider{value: val, isSet: true}
}

func (v NullableBaseDivider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseDivider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


