/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// ScreenProgressBarTitle struct for ScreenProgressBarTitle
type ScreenProgressBarTitle struct {
	NavigationBar NavigationBar `json:"navigationBar"`
	Footer Footer `json:"footer"`
	Styles BasicScreenBlock `json:"styles"`
	Permission NullableRequestPermission `json:"permission"`
	Timer NullableScreenTimer `json:"timer"`
	AnimationEnabled bool `json:"animationEnabled"`
	UseLocalAssetsIfAvailable bool `json:"useLocalAssetsIfAvailable"`
	ProgressBarTitleDescription string `json:"progressBarTitleDescription"`
	ProgressBar ProgressBar `json:"progressBar"`
	Title Text `json:"title"`
	Subtitle *Text `json:"subtitle,omitempty"`
}

// NewScreenProgressBarTitle instantiates a new ScreenProgressBarTitle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScreenProgressBarTitle(navigationBar NavigationBar, footer Footer, styles BasicScreenBlock, permission NullableRequestPermission, timer NullableScreenTimer, animationEnabled bool, useLocalAssetsIfAvailable bool, progressBarTitleDescription string, progressBar ProgressBar, title Text) *ScreenProgressBarTitle {
	this := ScreenProgressBarTitle{}
	this.NavigationBar = navigationBar
	this.Footer = footer
	this.Styles = styles
	this.Permission = permission
	this.Timer = timer
	this.AnimationEnabled = animationEnabled
	this.UseLocalAssetsIfAvailable = useLocalAssetsIfAvailable
	this.ProgressBarTitleDescription = progressBarTitleDescription
	this.ProgressBar = progressBar
	this.Title = title
	return &this
}

// NewScreenProgressBarTitleWithDefaults instantiates a new ScreenProgressBarTitle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScreenProgressBarTitleWithDefaults() *ScreenProgressBarTitle {
	this := ScreenProgressBarTitle{}
	return &this
}

// GetNavigationBar returns the NavigationBar field value
func (o *ScreenProgressBarTitle) GetNavigationBar() NavigationBar {
	if o == nil {
		var ret NavigationBar
		return ret
	}

	return o.NavigationBar
}

// GetNavigationBarOk returns a tuple with the NavigationBar field value
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetNavigationBarOk() (*NavigationBar, bool) {
	if o == nil {
    return nil, false
	}
	return &o.NavigationBar, true
}

// SetNavigationBar sets field value
func (o *ScreenProgressBarTitle) SetNavigationBar(v NavigationBar) {
	o.NavigationBar = v
}

// GetFooter returns the Footer field value
func (o *ScreenProgressBarTitle) GetFooter() Footer {
	if o == nil {
		var ret Footer
		return ret
	}

	return o.Footer
}

// GetFooterOk returns a tuple with the Footer field value
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetFooterOk() (*Footer, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Footer, true
}

// SetFooter sets field value
func (o *ScreenProgressBarTitle) SetFooter(v Footer) {
	o.Footer = v
}

// GetStyles returns the Styles field value
func (o *ScreenProgressBarTitle) GetStyles() BasicScreenBlock {
	if o == nil {
		var ret BasicScreenBlock
		return ret
	}

	return o.Styles
}

// GetStylesOk returns a tuple with the Styles field value
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetStylesOk() (*BasicScreenBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Styles, true
}

// SetStyles sets field value
func (o *ScreenProgressBarTitle) SetStyles(v BasicScreenBlock) {
	o.Styles = v
}

// GetPermission returns the Permission field value
// If the value is explicit nil, the zero value for RequestPermission will be returned
func (o *ScreenProgressBarTitle) GetPermission() RequestPermission {
	if o == nil || o.Permission.Get() == nil {
		var ret RequestPermission
		return ret
	}

	return *o.Permission.Get()
}

// GetPermissionOk returns a tuple with the Permission field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenProgressBarTitle) GetPermissionOk() (*RequestPermission, bool) {
	if o == nil {
    return nil, false
	}
	return o.Permission.Get(), o.Permission.IsSet()
}

// SetPermission sets field value
func (o *ScreenProgressBarTitle) SetPermission(v RequestPermission) {
	o.Permission.Set(&v)
}

// GetTimer returns the Timer field value
// If the value is explicit nil, the zero value for ScreenTimer will be returned
func (o *ScreenProgressBarTitle) GetTimer() ScreenTimer {
	if o == nil || o.Timer.Get() == nil {
		var ret ScreenTimer
		return ret
	}

	return *o.Timer.Get()
}

// GetTimerOk returns a tuple with the Timer field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenProgressBarTitle) GetTimerOk() (*ScreenTimer, bool) {
	if o == nil {
    return nil, false
	}
	return o.Timer.Get(), o.Timer.IsSet()
}

// SetTimer sets field value
func (o *ScreenProgressBarTitle) SetTimer(v ScreenTimer) {
	o.Timer.Set(&v)
}

// GetAnimationEnabled returns the AnimationEnabled field value
func (o *ScreenProgressBarTitle) GetAnimationEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AnimationEnabled
}

// GetAnimationEnabledOk returns a tuple with the AnimationEnabled field value
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetAnimationEnabledOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.AnimationEnabled, true
}

// SetAnimationEnabled sets field value
func (o *ScreenProgressBarTitle) SetAnimationEnabled(v bool) {
	o.AnimationEnabled = v
}

// GetUseLocalAssetsIfAvailable returns the UseLocalAssetsIfAvailable field value
func (o *ScreenProgressBarTitle) GetUseLocalAssetsIfAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UseLocalAssetsIfAvailable
}

// GetUseLocalAssetsIfAvailableOk returns a tuple with the UseLocalAssetsIfAvailable field value
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetUseLocalAssetsIfAvailableOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.UseLocalAssetsIfAvailable, true
}

// SetUseLocalAssetsIfAvailable sets field value
func (o *ScreenProgressBarTitle) SetUseLocalAssetsIfAvailable(v bool) {
	o.UseLocalAssetsIfAvailable = v
}

// GetProgressBarTitleDescription returns the ProgressBarTitleDescription field value
func (o *ScreenProgressBarTitle) GetProgressBarTitleDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProgressBarTitleDescription
}

// GetProgressBarTitleDescriptionOk returns a tuple with the ProgressBarTitleDescription field value
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetProgressBarTitleDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ProgressBarTitleDescription, true
}

// SetProgressBarTitleDescription sets field value
func (o *ScreenProgressBarTitle) SetProgressBarTitleDescription(v string) {
	o.ProgressBarTitleDescription = v
}

// GetProgressBar returns the ProgressBar field value
func (o *ScreenProgressBarTitle) GetProgressBar() ProgressBar {
	if o == nil {
		var ret ProgressBar
		return ret
	}

	return o.ProgressBar
}

// GetProgressBarOk returns a tuple with the ProgressBar field value
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetProgressBarOk() (*ProgressBar, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ProgressBar, true
}

// SetProgressBar sets field value
func (o *ScreenProgressBarTitle) SetProgressBar(v ProgressBar) {
	o.ProgressBar = v
}

// GetTitle returns the Title field value
func (o *ScreenProgressBarTitle) GetTitle() Text {
	if o == nil {
		var ret Text
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetTitleOk() (*Text, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ScreenProgressBarTitle) SetTitle(v Text) {
	o.Title = v
}

// GetSubtitle returns the Subtitle field value if set, zero value otherwise.
func (o *ScreenProgressBarTitle) GetSubtitle() Text {
	if o == nil || isNil(o.Subtitle) {
		var ret Text
		return ret
	}
	return *o.Subtitle
}

// GetSubtitleOk returns a tuple with the Subtitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenProgressBarTitle) GetSubtitleOk() (*Text, bool) {
	if o == nil || isNil(o.Subtitle) {
    return nil, false
	}
	return o.Subtitle, true
}

// HasSubtitle returns a boolean if a field has been set.
func (o *ScreenProgressBarTitle) HasSubtitle() bool {
	if o != nil && !isNil(o.Subtitle) {
		return true
	}

	return false
}

// SetSubtitle gets a reference to the given Text and assigns it to the Subtitle field.
func (o *ScreenProgressBarTitle) SetSubtitle(v Text) {
	o.Subtitle = &v
}

func (o ScreenProgressBarTitle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["navigationBar"] = o.NavigationBar
	}
	if true {
		toSerialize["footer"] = o.Footer
	}
	if true {
		toSerialize["styles"] = o.Styles
	}
	if true {
		toSerialize["permission"] = o.Permission.Get()
	}
	if true {
		toSerialize["timer"] = o.Timer.Get()
	}
	if true {
		toSerialize["animationEnabled"] = o.AnimationEnabled
	}
	if true {
		toSerialize["useLocalAssetsIfAvailable"] = o.UseLocalAssetsIfAvailable
	}
	if true {
		toSerialize["progressBarTitleDescription"] = o.ProgressBarTitleDescription
	}
	if true {
		toSerialize["progressBar"] = o.ProgressBar
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if !isNil(o.Subtitle) {
		toSerialize["subtitle"] = o.Subtitle
	}
	return json.Marshal(toSerialize)
}

type NullableScreenProgressBarTitle struct {
	value *ScreenProgressBarTitle
	isSet bool
}

func (v NullableScreenProgressBarTitle) Get() *ScreenProgressBarTitle {
	return v.value
}

func (v *NullableScreenProgressBarTitle) Set(val *ScreenProgressBarTitle) {
	v.value = val
	v.isSet = true
}

func (v NullableScreenProgressBarTitle) IsSet() bool {
	return v.isSet
}

func (v *NullableScreenProgressBarTitle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScreenProgressBarTitle(val *ScreenProgressBarTitle) *NullableScreenProgressBarTitle {
	return &NullableScreenProgressBarTitle{value: val, isSet: true}
}

func (v NullableScreenProgressBarTitle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScreenProgressBarTitle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


