/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// TwoColumnMultipleSelectionList Two column multiple selection list element
type TwoColumnMultipleSelectionList struct {
	ItemType TwoColumnMultipleSelectionListItemType `json:"itemType"`
	// Item rows
	Items []ItemTypeSelection `json:"items"`
	Styles ListBlock `json:"styles"`
	SelectedBlock SelectedListItemBlock `json:"selectedBlock"`
	Box Box `json:"box"`
}

// NewTwoColumnMultipleSelectionList instantiates a new TwoColumnMultipleSelectionList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoColumnMultipleSelectionList(itemType TwoColumnMultipleSelectionListItemType, items []ItemTypeSelection, styles ListBlock, selectedBlock SelectedListItemBlock, box Box) *TwoColumnMultipleSelectionList {
	this := TwoColumnMultipleSelectionList{}
	this.ItemType = itemType
	this.Items = items
	this.Styles = styles
	this.SelectedBlock = selectedBlock
	this.Box = box
	return &this
}

// NewTwoColumnMultipleSelectionListWithDefaults instantiates a new TwoColumnMultipleSelectionList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoColumnMultipleSelectionListWithDefaults() *TwoColumnMultipleSelectionList {
	this := TwoColumnMultipleSelectionList{}
	return &this
}

// GetItemType returns the ItemType field value
func (o *TwoColumnMultipleSelectionList) GetItemType() TwoColumnMultipleSelectionListItemType {
	if o == nil {
		var ret TwoColumnMultipleSelectionListItemType
		return ret
	}

	return o.ItemType
}

// GetItemTypeOk returns a tuple with the ItemType field value
// and a boolean to check if the value has been set.
func (o *TwoColumnMultipleSelectionList) GetItemTypeOk() (*TwoColumnMultipleSelectionListItemType, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ItemType, true
}

// SetItemType sets field value
func (o *TwoColumnMultipleSelectionList) SetItemType(v TwoColumnMultipleSelectionListItemType) {
	o.ItemType = v
}

// GetItems returns the Items field value
func (o *TwoColumnMultipleSelectionList) GetItems() []ItemTypeSelection {
	if o == nil {
		var ret []ItemTypeSelection
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *TwoColumnMultipleSelectionList) GetItemsOk() ([]ItemTypeSelection, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *TwoColumnMultipleSelectionList) SetItems(v []ItemTypeSelection) {
	o.Items = v
}

// GetStyles returns the Styles field value
func (o *TwoColumnMultipleSelectionList) GetStyles() ListBlock {
	if o == nil {
		var ret ListBlock
		return ret
	}

	return o.Styles
}

// GetStylesOk returns a tuple with the Styles field value
// and a boolean to check if the value has been set.
func (o *TwoColumnMultipleSelectionList) GetStylesOk() (*ListBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Styles, true
}

// SetStyles sets field value
func (o *TwoColumnMultipleSelectionList) SetStyles(v ListBlock) {
	o.Styles = v
}

// GetSelectedBlock returns the SelectedBlock field value
func (o *TwoColumnMultipleSelectionList) GetSelectedBlock() SelectedListItemBlock {
	if o == nil {
		var ret SelectedListItemBlock
		return ret
	}

	return o.SelectedBlock
}

// GetSelectedBlockOk returns a tuple with the SelectedBlock field value
// and a boolean to check if the value has been set.
func (o *TwoColumnMultipleSelectionList) GetSelectedBlockOk() (*SelectedListItemBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SelectedBlock, true
}

// SetSelectedBlock sets field value
func (o *TwoColumnMultipleSelectionList) SetSelectedBlock(v SelectedListItemBlock) {
	o.SelectedBlock = v
}

// GetBox returns the Box field value
func (o *TwoColumnMultipleSelectionList) GetBox() Box {
	if o == nil {
		var ret Box
		return ret
	}

	return o.Box
}

// GetBoxOk returns a tuple with the Box field value
// and a boolean to check if the value has been set.
func (o *TwoColumnMultipleSelectionList) GetBoxOk() (*Box, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Box, true
}

// SetBox sets field value
func (o *TwoColumnMultipleSelectionList) SetBox(v Box) {
	o.Box = v
}

func (o TwoColumnMultipleSelectionList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["itemType"] = o.ItemType
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["styles"] = o.Styles
	}
	if true {
		toSerialize["selectedBlock"] = o.SelectedBlock
	}
	if true {
		toSerialize["box"] = o.Box
	}
	return json.Marshal(toSerialize)
}

type NullableTwoColumnMultipleSelectionList struct {
	value *TwoColumnMultipleSelectionList
	isSet bool
}

func (v NullableTwoColumnMultipleSelectionList) Get() *TwoColumnMultipleSelectionList {
	return v.value
}

func (v *NullableTwoColumnMultipleSelectionList) Set(val *TwoColumnMultipleSelectionList) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoColumnMultipleSelectionList) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoColumnMultipleSelectionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoColumnMultipleSelectionList(val *TwoColumnMultipleSelectionList) *NullableTwoColumnMultipleSelectionList {
	return &NullableTwoColumnMultipleSelectionList{value: val, isSet: true}
}

func (v NullableTwoColumnMultipleSelectionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoColumnMultipleSelectionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


