/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// CustomScreenAllOf Custom screen
type CustomScreenAllOf struct {
	CustomScreenDescription string `json:"customScreenDescription"`
	// Dictionary of output labels for custom screen
	Labels map[string]CustomScreenOutputLabel `json:"labels"`
	// Dictionary of input values from custom screen
	Values map[string]CustomScreenInputValue `json:"values"`
	Callback Callback `json:"callback"`
}

// NewCustomScreenAllOf instantiates a new CustomScreenAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomScreenAllOf(customScreenDescription string, labels map[string]CustomScreenOutputLabel, values map[string]CustomScreenInputValue, callback Callback) *CustomScreenAllOf {
	this := CustomScreenAllOf{}
	this.CustomScreenDescription = customScreenDescription
	this.Labels = labels
	this.Values = values
	this.Callback = callback
	return &this
}

// NewCustomScreenAllOfWithDefaults instantiates a new CustomScreenAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomScreenAllOfWithDefaults() *CustomScreenAllOf {
	this := CustomScreenAllOf{}
	return &this
}

// GetCustomScreenDescription returns the CustomScreenDescription field value
func (o *CustomScreenAllOf) GetCustomScreenDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomScreenDescription
}

// GetCustomScreenDescriptionOk returns a tuple with the CustomScreenDescription field value
// and a boolean to check if the value has been set.
func (o *CustomScreenAllOf) GetCustomScreenDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.CustomScreenDescription, true
}

// SetCustomScreenDescription sets field value
func (o *CustomScreenAllOf) SetCustomScreenDescription(v string) {
	o.CustomScreenDescription = v
}

// GetLabels returns the Labels field value
func (o *CustomScreenAllOf) GetLabels() map[string]CustomScreenOutputLabel {
	if o == nil {
		var ret map[string]CustomScreenOutputLabel
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *CustomScreenAllOf) GetLabelsOk() (*map[string]CustomScreenOutputLabel, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *CustomScreenAllOf) SetLabels(v map[string]CustomScreenOutputLabel) {
	o.Labels = v
}

// GetValues returns the Values field value
func (o *CustomScreenAllOf) GetValues() map[string]CustomScreenInputValue {
	if o == nil {
		var ret map[string]CustomScreenInputValue
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *CustomScreenAllOf) GetValuesOk() (*map[string]CustomScreenInputValue, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Values, true
}

// SetValues sets field value
func (o *CustomScreenAllOf) SetValues(v map[string]CustomScreenInputValue) {
	o.Values = v
}

// GetCallback returns the Callback field value
func (o *CustomScreenAllOf) GetCallback() Callback {
	if o == nil {
		var ret Callback
		return ret
	}

	return o.Callback
}

// GetCallbackOk returns a tuple with the Callback field value
// and a boolean to check if the value has been set.
func (o *CustomScreenAllOf) GetCallbackOk() (*Callback, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Callback, true
}

// SetCallback sets field value
func (o *CustomScreenAllOf) SetCallback(v Callback) {
	o.Callback = v
}

func (o CustomScreenAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["customScreenDescription"] = o.CustomScreenDescription
	}
	if true {
		toSerialize["labels"] = o.Labels
	}
	if true {
		toSerialize["values"] = o.Values
	}
	if true {
		toSerialize["callback"] = o.Callback
	}
	return json.Marshal(toSerialize)
}

type NullableCustomScreenAllOf struct {
	value *CustomScreenAllOf
	isSet bool
}

func (v NullableCustomScreenAllOf) Get() *CustomScreenAllOf {
	return v.value
}

func (v *NullableCustomScreenAllOf) Set(val *CustomScreenAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomScreenAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomScreenAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomScreenAllOf(val *CustomScreenAllOf) *NullableCustomScreenAllOf {
	return &NullableCustomScreenAllOf{value: val, isSet: true}
}

func (v NullableCustomScreenAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomScreenAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


