package models
// MultipleSelectionListItemType : Combination of fields for multiple selection list item
type MultipleSelectionListItemType string

// List of MultipleSelectionListItemType
const (
	MULTIPLESELECTIONLISTITEMTYPE_TITLE_SUBTITLE_CHECKBOX MultipleSelectionListItemType = "TitleSubtitleCheckbox"
	MULTIPLESELECTIONLISTITEMTYPE_CHECKBOX_TITLE_SUBTITLE MultipleSelectionListItemType = "CheckboxTitleSubtitle"
	MULTIPLESELECTIONLISTITEMTYPE_TITLE_SUBTITLE MultipleSelectionListItemType = "TitleSubtitle"
	MULTIPLESELECTIONLISTITEMTYPE_TITLE MultipleSelectionListItemType = "Title"
	MULTIPLESELECTIONLISTITEMTYPE_IMAGE_TITLE_SUBTITLE_CHECKBOX MultipleSelectionListItemType = "ImageTitleSubtitleCheckbox"
	MULTIPLESELECTIONLISTITEMTYPE_CHECKBOX_TITLE_SUBTITLE_IMAGE MultipleSelectionListItemType = "CheckboxTitleSubtitleImage"
	MULTIPLESELECTIONLISTITEMTYPE_IMAGE_TITLE_CHECKBOX MultipleSelectionListItemType = "ImageTitleCheckbox"
	MULTIPLESELECTIONLISTITEMTYPE_CHECKBOX_TITLE_IMAGE MultipleSelectionListItemType = "CheckboxTitleImage"
	MULTIPLESELECTIONLISTITEMTYPE_TITLE_CHECKBOX MultipleSelectionListItemType = "TitleCheckbox"
	MULTIPLESELECTIONLISTITEMTYPE_CHECKBOX_TITLE MultipleSelectionListItemType = "CheckboxTitle"
	MULTIPLESELECTIONLISTITEMTYPE_TITLE_IMAGE MultipleSelectionListItemType = "TitleImage"
	MULTIPLESELECTIONLISTITEMTYPE_IMAGE_TITLE MultipleSelectionListItemType = "ImageTitle"
	MULTIPLESELECTIONLISTITEMTYPE_IMAGE_TITLE_SUBTITLE MultipleSelectionListItemType = "ImageTitleSubtitle"
	MULTIPLESELECTIONLISTITEMTYPE_TITLE_SUBTITLE_IMAGE MultipleSelectionListItemType = "TitleSubtitleImage"
)
