/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
)

// BasicPaywallBodyKind Basic paywall body kind
type BasicPaywallBodyKind string

// List of BasicPaywallBodyKind
const (
	BASICPAYWALLBODYKIND_MASK BasicPaywallBodyKind = "mask"
	BASICPAYWALLBODYKIND_GRADIENT BasicPaywallBodyKind = "gradient"
)

// All allowed values of BasicPaywallBodyKind enum
var AllowedBasicPaywallBodyKindEnumValues = []BasicPaywallBodyKind{
	"mask",
	"gradient",
}

func (v *BasicPaywallBodyKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BasicPaywallBodyKind(value)
	for _, existing := range AllowedBasicPaywallBodyKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BasicPaywallBodyKind", value)
}

// NewBasicPaywallBodyKindFromValue returns a pointer to a valid BasicPaywallBodyKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBasicPaywallBodyKindFromValue(v string) (*BasicPaywallBodyKind, error) {
	ev := BasicPaywallBodyKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BasicPaywallBodyKind: valid values are %v", v, AllowedBasicPaywallBodyKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BasicPaywallBodyKind) IsValid() bool {
	for _, existing := range AllowedBasicPaywallBodyKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BasicPaywallBodyKind value
func (v BasicPaywallBodyKind) Ptr() *BasicPaywallBodyKind {
	return &v
}

type NullableBasicPaywallBodyKind struct {
	value *BasicPaywallBodyKind
	isSet bool
}

func (v NullableBasicPaywallBodyKind) Get() *BasicPaywallBodyKind {
	return v.value
}

func (v *NullableBasicPaywallBodyKind) Set(val *BasicPaywallBodyKind) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicPaywallBodyKind) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicPaywallBodyKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicPaywallBodyKind(val *BasicPaywallBodyKind) *NullableBasicPaywallBodyKind {
	return &NullableBasicPaywallBodyKind{value: val, isSet: true}
}

func (v NullableBasicPaywallBodyKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicPaywallBodyKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

