/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// SingleSelectionList Single selection list element
type SingleSelectionList struct {
	ItemType SingleSelectionListItemType `json:"itemType"`
	// Item rows
	Items []ItemTypeSelection `json:"items"`
	Styles ListBlock `json:"styles"`
	SelectedBlock SelectedListItemBlock `json:"selectedBlock"`
	Box Box `json:"box"`
}

// NewSingleSelectionList instantiates a new SingleSelectionList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSingleSelectionList(itemType SingleSelectionListItemType, items []ItemTypeSelection, styles ListBlock, selectedBlock SelectedListItemBlock, box Box) *SingleSelectionList {
	this := SingleSelectionList{}
	this.ItemType = itemType
	this.Items = items
	this.Styles = styles
	this.SelectedBlock = selectedBlock
	this.Box = box
	return &this
}

// NewSingleSelectionListWithDefaults instantiates a new SingleSelectionList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSingleSelectionListWithDefaults() *SingleSelectionList {
	this := SingleSelectionList{}
	return &this
}

// GetItemType returns the ItemType field value
func (o *SingleSelectionList) GetItemType() SingleSelectionListItemType {
	if o == nil {
		var ret SingleSelectionListItemType
		return ret
	}

	return o.ItemType
}

// GetItemTypeOk returns a tuple with the ItemType field value
// and a boolean to check if the value has been set.
func (o *SingleSelectionList) GetItemTypeOk() (*SingleSelectionListItemType, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ItemType, true
}

// SetItemType sets field value
func (o *SingleSelectionList) SetItemType(v SingleSelectionListItemType) {
	o.ItemType = v
}

// GetItems returns the Items field value
func (o *SingleSelectionList) GetItems() []ItemTypeSelection {
	if o == nil {
		var ret []ItemTypeSelection
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SingleSelectionList) GetItemsOk() ([]ItemTypeSelection, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SingleSelectionList) SetItems(v []ItemTypeSelection) {
	o.Items = v
}

// GetStyles returns the Styles field value
func (o *SingleSelectionList) GetStyles() ListBlock {
	if o == nil {
		var ret ListBlock
		return ret
	}

	return o.Styles
}

// GetStylesOk returns a tuple with the Styles field value
// and a boolean to check if the value has been set.
func (o *SingleSelectionList) GetStylesOk() (*ListBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Styles, true
}

// SetStyles sets field value
func (o *SingleSelectionList) SetStyles(v ListBlock) {
	o.Styles = v
}

// GetSelectedBlock returns the SelectedBlock field value
func (o *SingleSelectionList) GetSelectedBlock() SelectedListItemBlock {
	if o == nil {
		var ret SelectedListItemBlock
		return ret
	}

	return o.SelectedBlock
}

// GetSelectedBlockOk returns a tuple with the SelectedBlock field value
// and a boolean to check if the value has been set.
func (o *SingleSelectionList) GetSelectedBlockOk() (*SelectedListItemBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SelectedBlock, true
}

// SetSelectedBlock sets field value
func (o *SingleSelectionList) SetSelectedBlock(v SelectedListItemBlock) {
	o.SelectedBlock = v
}

// GetBox returns the Box field value
func (o *SingleSelectionList) GetBox() Box {
	if o == nil {
		var ret Box
		return ret
	}

	return o.Box
}

// GetBoxOk returns a tuple with the Box field value
// and a boolean to check if the value has been set.
func (o *SingleSelectionList) GetBoxOk() (*Box, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Box, true
}

// SetBox sets field value
func (o *SingleSelectionList) SetBox(v Box) {
	o.Box = v
}

func (o SingleSelectionList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["itemType"] = o.ItemType
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["styles"] = o.Styles
	}
	if true {
		toSerialize["selectedBlock"] = o.SelectedBlock
	}
	if true {
		toSerialize["box"] = o.Box
	}
	return json.Marshal(toSerialize)
}

type NullableSingleSelectionList struct {
	value *SingleSelectionList
	isSet bool
}

func (v NullableSingleSelectionList) Get() *SingleSelectionList {
	return v.value
}

func (v *NullableSingleSelectionList) Set(val *SingleSelectionList) {
	v.value = val
	v.isSet = true
}

func (v NullableSingleSelectionList) IsSet() bool {
	return v.isSet
}

func (v *NullableSingleSelectionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSingleSelectionList(val *SingleSelectionList) *NullableSingleSelectionList {
	return &NullableSingleSelectionList{value: val, isSet: true}
}

func (v NullableSingleSelectionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSingleSelectionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


