/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// SlideContent Slide content
type SlideContent struct {
	Image Image `json:"image"`
	Title Text `json:"title"`
	Subtitle1 Text `json:"subtitle1"`
	Subtitle2 Text `json:"subtitle2"`
}

// NewSlideContent instantiates a new SlideContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlideContent(image Image, title Text, subtitle1 Text, subtitle2 Text) *SlideContent {
	this := SlideContent{}
	this.Image = image
	this.Title = title
	this.Subtitle1 = subtitle1
	this.Subtitle2 = subtitle2
	return &this
}

// NewSlideContentWithDefaults instantiates a new SlideContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlideContentWithDefaults() *SlideContent {
	this := SlideContent{}
	return &this
}

// GetImage returns the Image field value
func (o *SlideContent) GetImage() Image {
	if o == nil {
		var ret Image
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *SlideContent) GetImageOk() (*Image, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *SlideContent) SetImage(v Image) {
	o.Image = v
}

// GetTitle returns the Title field value
func (o *SlideContent) GetTitle() Text {
	if o == nil {
		var ret Text
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *SlideContent) GetTitleOk() (*Text, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *SlideContent) SetTitle(v Text) {
	o.Title = v
}

// GetSubtitle1 returns the Subtitle1 field value
func (o *SlideContent) GetSubtitle1() Text {
	if o == nil {
		var ret Text
		return ret
	}

	return o.Subtitle1
}

// GetSubtitle1Ok returns a tuple with the Subtitle1 field value
// and a boolean to check if the value has been set.
func (o *SlideContent) GetSubtitle1Ok() (*Text, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Subtitle1, true
}

// SetSubtitle1 sets field value
func (o *SlideContent) SetSubtitle1(v Text) {
	o.Subtitle1 = v
}

// GetSubtitle2 returns the Subtitle2 field value
func (o *SlideContent) GetSubtitle2() Text {
	if o == nil {
		var ret Text
		return ret
	}

	return o.Subtitle2
}

// GetSubtitle2Ok returns a tuple with the Subtitle2 field value
// and a boolean to check if the value has been set.
func (o *SlideContent) GetSubtitle2Ok() (*Text, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Subtitle2, true
}

// SetSubtitle2 sets field value
func (o *SlideContent) SetSubtitle2(v Text) {
	o.Subtitle2 = v
}

func (o SlideContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["image"] = o.Image
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["subtitle1"] = o.Subtitle1
	}
	if true {
		toSerialize["subtitle2"] = o.Subtitle2
	}
	return json.Marshal(toSerialize)
}

type NullableSlideContent struct {
	value *SlideContent
	isSet bool
}

func (v NullableSlideContent) Get() *SlideContent {
	return v.value
}

func (v *NullableSlideContent) Set(val *SlideContent) {
	v.value = val
	v.isSet = true
}

func (v NullableSlideContent) IsSet() bool {
	return v.isSet
}

func (v *NullableSlideContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlideContent(val *SlideContent) *NullableSlideContent {
	return &NullableSlideContent{value: val, isSet: true}
}

func (v NullableSlideContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlideContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


