/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// ScreenTooltipPermissionsAllOf Screen - Tooltip/Permissions
type ScreenTooltipPermissionsAllOf struct {
	TooltipPermissionsDescription string `json:"tooltipPermissionsDescription"`
	Tooltip Tooltip `json:"tooltip"`
}

// NewScreenTooltipPermissionsAllOf instantiates a new ScreenTooltipPermissionsAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScreenTooltipPermissionsAllOf(tooltipPermissionsDescription string, tooltip Tooltip) *ScreenTooltipPermissionsAllOf {
	this := ScreenTooltipPermissionsAllOf{}
	this.TooltipPermissionsDescription = tooltipPermissionsDescription
	this.Tooltip = tooltip
	return &this
}

// NewScreenTooltipPermissionsAllOfWithDefaults instantiates a new ScreenTooltipPermissionsAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScreenTooltipPermissionsAllOfWithDefaults() *ScreenTooltipPermissionsAllOf {
	this := ScreenTooltipPermissionsAllOf{}
	return &this
}

// GetTooltipPermissionsDescription returns the TooltipPermissionsDescription field value
func (o *ScreenTooltipPermissionsAllOf) GetTooltipPermissionsDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TooltipPermissionsDescription
}

// GetTooltipPermissionsDescriptionOk returns a tuple with the TooltipPermissionsDescription field value
// and a boolean to check if the value has been set.
func (o *ScreenTooltipPermissionsAllOf) GetTooltipPermissionsDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TooltipPermissionsDescription, true
}

// SetTooltipPermissionsDescription sets field value
func (o *ScreenTooltipPermissionsAllOf) SetTooltipPermissionsDescription(v string) {
	o.TooltipPermissionsDescription = v
}

// GetTooltip returns the Tooltip field value
func (o *ScreenTooltipPermissionsAllOf) GetTooltip() Tooltip {
	if o == nil {
		var ret Tooltip
		return ret
	}

	return o.Tooltip
}

// GetTooltipOk returns a tuple with the Tooltip field value
// and a boolean to check if the value has been set.
func (o *ScreenTooltipPermissionsAllOf) GetTooltipOk() (*Tooltip, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Tooltip, true
}

// SetTooltip sets field value
func (o *ScreenTooltipPermissionsAllOf) SetTooltip(v Tooltip) {
	o.Tooltip = v
}

func (o ScreenTooltipPermissionsAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["tooltipPermissionsDescription"] = o.TooltipPermissionsDescription
	}
	if true {
		toSerialize["tooltip"] = o.Tooltip
	}
	return json.Marshal(toSerialize)
}

type NullableScreenTooltipPermissionsAllOf struct {
	value *ScreenTooltipPermissionsAllOf
	isSet bool
}

func (v NullableScreenTooltipPermissionsAllOf) Get() *ScreenTooltipPermissionsAllOf {
	return v.value
}

func (v *NullableScreenTooltipPermissionsAllOf) Set(val *ScreenTooltipPermissionsAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableScreenTooltipPermissionsAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableScreenTooltipPermissionsAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScreenTooltipPermissionsAllOf(val *ScreenTooltipPermissionsAllOf) *NullableScreenTooltipPermissionsAllOf {
	return &NullableScreenTooltipPermissionsAllOf{value: val, isSet: true}
}

func (v NullableScreenTooltipPermissionsAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScreenTooltipPermissionsAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


