/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// TemplateParameters Template parameters
type TemplateParameters struct {
	// Dictionary of labels styles
	Labels map[string]LabelBlock `json:"labels"`
	// Template link dictionary
	Links map[string]string `json:"links"`
}

// NewTemplateParameters instantiates a new TemplateParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateParameters(labels map[string]LabelBlock, links map[string]string) *TemplateParameters {
	this := TemplateParameters{}
	this.Labels = labels
	this.Links = links
	return &this
}

// NewTemplateParametersWithDefaults instantiates a new TemplateParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateParametersWithDefaults() *TemplateParameters {
	this := TemplateParameters{}
	return &this
}

// GetLabels returns the Labels field value
func (o *TemplateParameters) GetLabels() map[string]LabelBlock {
	if o == nil {
		var ret map[string]LabelBlock
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *TemplateParameters) GetLabelsOk() (*map[string]LabelBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *TemplateParameters) SetLabels(v map[string]LabelBlock) {
	o.Labels = v
}

// GetLinks returns the Links field value
func (o *TemplateParameters) GetLinks() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *TemplateParameters) GetLinksOk() (*map[string]string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *TemplateParameters) SetLinks(v map[string]string) {
	o.Links = v
}

func (o TemplateParameters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["labels"] = o.Labels
	}
	if true {
		toSerialize["links"] = o.Links
	}
	return json.Marshal(toSerialize)
}

type NullableTemplateParameters struct {
	value *TemplateParameters
	isSet bool
}

func (v NullableTemplateParameters) Get() *TemplateParameters {
	return v.value
}

func (v *NullableTemplateParameters) Set(val *TemplateParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateParameters(val *TemplateParameters) *NullableTemplateParameters {
	return &NullableTemplateParameters{value: val, isSet: true}
}

func (v NullableTemplateParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


