/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// Loader Loader parameters
type Loader struct {
	Box Box `json:"box"`
	Kind LoaderKind `json:"kind"`
	Styles LoaderBlock `json:"styles"`
}

// NewLoader instantiates a new Loader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoader(box Box, kind LoaderKind, styles LoaderBlock) *Loader {
	this := Loader{}
	this.Kind = kind
	this.Styles = styles
	return &this
}

// NewLoaderWithDefaults instantiates a new Loader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoaderWithDefaults() *Loader {
	this := Loader{}
	return &this
}

// GetBox returns the Box field value
func (o *Loader) GetBox() Box {
	if o == nil {
		var ret Box
		return ret
	}

	return o.Box
}

// GetBoxOk returns a tuple with the Box field value
// and a boolean to check if the value has been set.
func (o *Loader) GetBoxOk() (*Box, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Box, true
}

// SetBox sets field value
func (o *Loader) SetBox(v Box) {
	o.Box = v
}

// GetKind returns the Kind field value
func (o *Loader) GetKind() LoaderKind {
	if o == nil {
		var ret LoaderKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *Loader) GetKindOk() (*LoaderKind, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *Loader) SetKind(v LoaderKind) {
	o.Kind = v
}

// GetStyles returns the Styles field value
func (o *Loader) GetStyles() LoaderBlock {
	if o == nil {
		var ret LoaderBlock
		return ret
	}

	return o.Styles
}

// GetStylesOk returns a tuple with the Styles field value
// and a boolean to check if the value has been set.
func (o *Loader) GetStylesOk() (*LoaderBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Styles, true
}

// SetStyles sets field value
func (o *Loader) SetStyles(v LoaderBlock) {
	o.Styles = v
}

func (o Loader) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["box"] = o.Box
	}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["styles"] = o.Styles
	}
	return json.Marshal(toSerialize)
}

type NullableLoader struct {
	value *Loader
	isSet bool
}

func (v NullableLoader) Get() *Loader {
	return v.value
}

func (v *NullableLoader) Set(val *Loader) {
	v.value = val
	v.isSet = true
}

func (v NullableLoader) IsSet() bool {
	return v.isSet
}

func (v *NullableLoader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoader(val *Loader) *NullableLoader {
	return &NullableLoader{value: val, isSet: true}
}

func (v NullableLoader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


