/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// BaseCheckBox Base checkbox parameters
type BaseCheckBox struct {
	Kind CheckBoxKind `json:"kind"`
	// Flag if checkbox checked
	Checked bool `json:"checked"`
	Styles CheckBoxBlock `json:"styles"`
	SelectedBlock SelectedCheckBoxBlock `json:"selectedBlock"`
}

// NewBaseCheckBox instantiates a new BaseCheckBox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseCheckBox(kind CheckBoxKind, checked bool, styles CheckBoxBlock, selectedBlock SelectedCheckBoxBlock) *BaseCheckBox {
	this := BaseCheckBox{}
	this.Kind = kind
	this.Checked = checked
	this.Styles = styles
	this.SelectedBlock = selectedBlock
	return &this
}

// NewBaseCheckBoxWithDefaults instantiates a new BaseCheckBox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseCheckBoxWithDefaults() *BaseCheckBox {
	this := BaseCheckBox{}
	return &this
}

// GetKind returns the Kind field value
func (o *BaseCheckBox) GetKind() CheckBoxKind {
	if o == nil {
		var ret CheckBoxKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *BaseCheckBox) GetKindOk() (*CheckBoxKind, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *BaseCheckBox) SetKind(v CheckBoxKind) {
	o.Kind = v
}

// GetChecked returns the Checked field value
func (o *BaseCheckBox) GetChecked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Checked
}

// GetCheckedOk returns a tuple with the Checked field value
// and a boolean to check if the value has been set.
func (o *BaseCheckBox) GetCheckedOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Checked, true
}

// SetChecked sets field value
func (o *BaseCheckBox) SetChecked(v bool) {
	o.Checked = v
}

// GetStyles returns the Styles field value
func (o *BaseCheckBox) GetStyles() CheckBoxBlock {
	if o == nil {
		var ret CheckBoxBlock
		return ret
	}

	return o.Styles
}

// GetStylesOk returns a tuple with the Styles field value
// and a boolean to check if the value has been set.
func (o *BaseCheckBox) GetStylesOk() (*CheckBoxBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Styles, true
}

// SetStyles sets field value
func (o *BaseCheckBox) SetStyles(v CheckBoxBlock) {
	o.Styles = v
}

// GetSelectedBlock returns the SelectedBlock field value
func (o *BaseCheckBox) GetSelectedBlock() SelectedCheckBoxBlock {
	if o == nil {
		var ret SelectedCheckBoxBlock
		return ret
	}

	return o.SelectedBlock
}

// GetSelectedBlockOk returns a tuple with the SelectedBlock field value
// and a boolean to check if the value has been set.
func (o *BaseCheckBox) GetSelectedBlockOk() (*SelectedCheckBoxBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SelectedBlock, true
}

// SetSelectedBlock sets field value
func (o *BaseCheckBox) SetSelectedBlock(v SelectedCheckBoxBlock) {
	o.SelectedBlock = v
}

func (o BaseCheckBox) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["checked"] = o.Checked
	}
	if true {
		toSerialize["styles"] = o.Styles
	}
	if true {
		toSerialize["selectedBlock"] = o.SelectedBlock
	}
	return json.Marshal(toSerialize)
}

type NullableBaseCheckBox struct {
	value *BaseCheckBox
	isSet bool
}

func (v NullableBaseCheckBox) Get() *BaseCheckBox {
	return v.value
}

func (v *NullableBaseCheckBox) Set(val *BaseCheckBox) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseCheckBox) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseCheckBox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseCheckBox(val *BaseCheckBox) *NullableBaseCheckBox {
	return &NullableBaseCheckBox{value: val, isSet: true}
}

func (v NullableBaseCheckBox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseCheckBox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


