/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// BackgroundStyleVideo Background video
type BackgroundStyleVideo struct {
	Video BaseVideo `json:"video"`
}

// NewBackgroundStyleVideo instantiates a new BackgroundStyleVideo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackgroundStyleVideo(video BaseVideo) *BackgroundStyleVideo {
	this := BackgroundStyleVideo{}
	this.Video = video
	return &this
}

// NewBackgroundStyleVideoWithDefaults instantiates a new BackgroundStyleVideo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackgroundStyleVideoWithDefaults() *BackgroundStyleVideo {
	this := BackgroundStyleVideo{}
	return &this
}

// GetVideo returns the Video field value
func (o *BackgroundStyleVideo) GetVideo() BaseVideo {
	if o == nil {
		var ret BaseVideo
		return ret
	}

	return o.Video
}

// GetVideoOk returns a tuple with the Video field value
// and a boolean to check if the value has been set.
func (o *BackgroundStyleVideo) GetVideoOk() (*BaseVideo, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Video, true
}

// SetVideo sets field value
func (o *BackgroundStyleVideo) SetVideo(v BaseVideo) {
	o.Video = v
}

func (o BackgroundStyleVideo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["video"] = o.Video
	}
	return json.Marshal(toSerialize)
}

type NullableBackgroundStyleVideo struct {
	value *BackgroundStyleVideo
	isSet bool
}

func (v NullableBackgroundStyleVideo) Get() *BackgroundStyleVideo {
	return v.value
}

func (v *NullableBackgroundStyleVideo) Set(val *BackgroundStyleVideo) {
	v.value = val
	v.isSet = true
}

func (v NullableBackgroundStyleVideo) IsSet() bool {
	return v.isSet
}

func (v *NullableBackgroundStyleVideo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackgroundStyleVideo(val *BackgroundStyleVideo) *NullableBackgroundStyleVideo {
	return &NullableBackgroundStyleVideo{value: val, isSet: true}
}

func (v NullableBackgroundStyleVideo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackgroundStyleVideo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


