/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// Image Image parameters
type Image struct {
	Box Box `json:"box"`
	// Dictionary of localized Asset
	L10n map[string]Asset `json:"l10n"`
	Styles ImageBlock `json:"styles"`
}

// NewImage instantiates a new Image object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImage(box Box, l10n map[string]Asset, styles ImageBlock) *Image {
	this := Image{}
	this.L10n = l10n
	this.Styles = styles
	return &this
}

// NewImageWithDefaults instantiates a new Image object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageWithDefaults() *Image {
	this := Image{}
	return &this
}

// GetBox returns the Box field value
func (o *Image) GetBox() Box {
	if o == nil {
		var ret Box
		return ret
	}

	return o.Box
}

// GetBoxOk returns a tuple with the Box field value
// and a boolean to check if the value has been set.
func (o *Image) GetBoxOk() (*Box, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Box, true
}

// SetBox sets field value
func (o *Image) SetBox(v Box) {
	o.Box = v
}

// GetL10n returns the L10n field value
func (o *Image) GetL10n() map[string]Asset {
	if o == nil {
		var ret map[string]Asset
		return ret
	}

	return o.L10n
}

// GetL10nOk returns a tuple with the L10n field value
// and a boolean to check if the value has been set.
func (o *Image) GetL10nOk() (*map[string]Asset, bool) {
	if o == nil {
    return nil, false
	}
	return &o.L10n, true
}

// SetL10n sets field value
func (o *Image) SetL10n(v map[string]Asset) {
	o.L10n = v
}

// GetStyles returns the Styles field value
func (o *Image) GetStyles() ImageBlock {
	if o == nil {
		var ret ImageBlock
		return ret
	}

	return o.Styles
}

// GetStylesOk returns a tuple with the Styles field value
// and a boolean to check if the value has been set.
func (o *Image) GetStylesOk() (*ImageBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Styles, true
}

// SetStyles sets field value
func (o *Image) SetStyles(v ImageBlock) {
	o.Styles = v
}

func (o Image) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["box"] = o.Box
	}
	if true {
		toSerialize["l10n"] = o.L10n
	}
	if true {
		toSerialize["styles"] = o.Styles
	}
	return json.Marshal(toSerialize)
}

type NullableImage struct {
	value *Image
	isSet bool
}

func (v NullableImage) Get() *Image {
	return v.value
}

func (v *NullableImage) Set(val *Image) {
	v.value = val
	v.isSet = true
}

func (v NullableImage) IsSet() bool {
	return v.isSet
}

func (v *NullableImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImage(val *Image) *NullableImage {
	return &NullableImage{value: val, isSet: true}
}

func (v NullableImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


