/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// ScreenTimer Timer to show the screen
type ScreenTimer struct {
	// Duration to show some screen in seconds
	Duration int32 `json:"duration"`
	Action Action `json:"action"`
	Unit *TimerUnit `json:"unit,omitempty"`
}

// NewScreenTimer instantiates a new ScreenTimer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScreenTimer(duration int32, action Action) *ScreenTimer {
	this := ScreenTimer{}
	this.Duration = duration
	this.Action = action
	return &this
}

// NewScreenTimerWithDefaults instantiates a new ScreenTimer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScreenTimerWithDefaults() *ScreenTimer {
	this := ScreenTimer{}
	return &this
}

// GetDuration returns the Duration field value
func (o *ScreenTimer) GetDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *ScreenTimer) GetDurationOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *ScreenTimer) SetDuration(v int32) {
	o.Duration = v
}

// GetAction returns the Action field value
func (o *ScreenTimer) GetAction() Action {
	if o == nil {
		var ret Action
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *ScreenTimer) GetActionOk() (*Action, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *ScreenTimer) SetAction(v Action) {
	o.Action = v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *ScreenTimer) GetUnit() TimerUnit {
	if o == nil || isNil(o.Unit) {
		var ret TimerUnit
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenTimer) GetUnitOk() (*TimerUnit, bool) {
	if o == nil || isNil(o.Unit) {
    return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *ScreenTimer) HasUnit() bool {
	if o != nil && !isNil(o.Unit) {
		return true
	}

	return false
}

// SetUnit gets a reference to the given TimerUnit and assigns it to the Unit field.
func (o *ScreenTimer) SetUnit(v TimerUnit) {
	o.Unit = &v
}

func (o ScreenTimer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["duration"] = o.Duration
	}
	if true {
		toSerialize["action"] = o.Action
	}
	if !isNil(o.Unit) {
		toSerialize["unit"] = o.Unit
	}
	return json.Marshal(toSerialize)
}

type NullableScreenTimer struct {
	value *ScreenTimer
	isSet bool
}

func (v NullableScreenTimer) Get() *ScreenTimer {
	return v.value
}

func (v *NullableScreenTimer) Set(val *ScreenTimer) {
	v.value = val
	v.isSet = true
}

func (v NullableScreenTimer) IsSet() bool {
	return v.isSet
}

func (v *NullableScreenTimer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScreenTimer(val *ScreenTimer) *NullableScreenTimer {
	return &NullableScreenTimer{value: val, isSet: true}
}

func (v NullableScreenTimer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScreenTimer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


