/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// CalendarDay Calendar day config
type CalendarDay struct {
	LabelBlock LabelBlock `json:"labelBlock"`
	SelectedLabelBlock LabelBlock `json:"selectedLabelBlock"`
	CheckBox BaseCheckBox `json:"checkBox"`
}

// NewCalendarDay instantiates a new CalendarDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarDay(labelBlock LabelBlock, selectedLabelBlock LabelBlock, checkBox BaseCheckBox) *CalendarDay {
	this := CalendarDay{}
	this.LabelBlock = labelBlock
	this.SelectedLabelBlock = selectedLabelBlock
	this.CheckBox = checkBox
	return &this
}

// NewCalendarDayWithDefaults instantiates a new CalendarDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarDayWithDefaults() *CalendarDay {
	this := CalendarDay{}
	return &this
}

// GetLabelBlock returns the LabelBlock field value
func (o *CalendarDay) GetLabelBlock() LabelBlock {
	if o == nil {
		var ret LabelBlock
		return ret
	}

	return o.LabelBlock
}

// GetLabelBlockOk returns a tuple with the LabelBlock field value
// and a boolean to check if the value has been set.
func (o *CalendarDay) GetLabelBlockOk() (*LabelBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.LabelBlock, true
}

// SetLabelBlock sets field value
func (o *CalendarDay) SetLabelBlock(v LabelBlock) {
	o.LabelBlock = v
}

// GetSelectedLabelBlock returns the SelectedLabelBlock field value
func (o *CalendarDay) GetSelectedLabelBlock() LabelBlock {
	if o == nil {
		var ret LabelBlock
		return ret
	}

	return o.SelectedLabelBlock
}

// GetSelectedLabelBlockOk returns a tuple with the SelectedLabelBlock field value
// and a boolean to check if the value has been set.
func (o *CalendarDay) GetSelectedLabelBlockOk() (*LabelBlock, bool) {
	if o == nil {
    return nil, false
	}
	return &o.SelectedLabelBlock, true
}

// SetSelectedLabelBlock sets field value
func (o *CalendarDay) SetSelectedLabelBlock(v LabelBlock) {
	o.SelectedLabelBlock = v
}

// GetCheckBox returns the CheckBox field value
func (o *CalendarDay) GetCheckBox() BaseCheckBox {
	if o == nil {
		var ret BaseCheckBox
		return ret
	}

	return o.CheckBox
}

// GetCheckBoxOk returns a tuple with the CheckBox field value
// and a boolean to check if the value has been set.
func (o *CalendarDay) GetCheckBoxOk() (*BaseCheckBox, bool) {
	if o == nil {
    return nil, false
	}
	return &o.CheckBox, true
}

// SetCheckBox sets field value
func (o *CalendarDay) SetCheckBox(v BaseCheckBox) {
	o.CheckBox = v
}

func (o CalendarDay) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["labelBlock"] = o.LabelBlock
	}
	if true {
		toSerialize["selectedLabelBlock"] = o.SelectedLabelBlock
	}
	if true {
		toSerialize["checkBox"] = o.CheckBox
	}
	return json.Marshal(toSerialize)
}

type NullableCalendarDay struct {
	value *CalendarDay
	isSet bool
}

func (v NullableCalendarDay) Get() *CalendarDay {
	return v.value
}

func (v *NullableCalendarDay) Set(val *CalendarDay) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarDay) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarDay(val *CalendarDay) *NullableCalendarDay {
	return &NullableCalendarDay{value: val, isSet: true}
}

func (v NullableCalendarDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


