/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// PageIndicatorBlock Styles for page indicator
type PageIndicatorBlock struct {
	// The line's color
	Color *string `json:"color,omitempty"`
	// The line's track color
	TrackColor *string `json:"trackColor,omitempty"`
}

// NewPageIndicatorBlock instantiates a new PageIndicatorBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageIndicatorBlock() *PageIndicatorBlock {
	this := PageIndicatorBlock{}
	return &this
}

// NewPageIndicatorBlockWithDefaults instantiates a new PageIndicatorBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageIndicatorBlockWithDefaults() *PageIndicatorBlock {
	this := PageIndicatorBlock{}
	return &this
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *PageIndicatorBlock) GetColor() string {
	if o == nil || isNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageIndicatorBlock) GetColorOk() (*string, bool) {
	if o == nil || isNil(o.Color) {
    return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *PageIndicatorBlock) HasColor() bool {
	if o != nil && !isNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *PageIndicatorBlock) SetColor(v string) {
	o.Color = &v
}

// GetTrackColor returns the TrackColor field value if set, zero value otherwise.
func (o *PageIndicatorBlock) GetTrackColor() string {
	if o == nil || isNil(o.TrackColor) {
		var ret string
		return ret
	}
	return *o.TrackColor
}

// GetTrackColorOk returns a tuple with the TrackColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageIndicatorBlock) GetTrackColorOk() (*string, bool) {
	if o == nil || isNil(o.TrackColor) {
    return nil, false
	}
	return o.TrackColor, true
}

// HasTrackColor returns a boolean if a field has been set.
func (o *PageIndicatorBlock) HasTrackColor() bool {
	if o != nil && !isNil(o.TrackColor) {
		return true
	}

	return false
}

// SetTrackColor gets a reference to the given string and assigns it to the TrackColor field.
func (o *PageIndicatorBlock) SetTrackColor(v string) {
	o.TrackColor = &v
}

func (o PageIndicatorBlock) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !isNil(o.TrackColor) {
		toSerialize["trackColor"] = o.TrackColor
	}
	return json.Marshal(toSerialize)
}

type NullablePageIndicatorBlock struct {
	value *PageIndicatorBlock
	isSet bool
}

func (v NullablePageIndicatorBlock) Get() *PageIndicatorBlock {
	return v.value
}

func (v *NullablePageIndicatorBlock) Set(val *PageIndicatorBlock) {
	v.value = val
	v.isSet = true
}

func (v NullablePageIndicatorBlock) IsSet() bool {
	return v.isSet
}

func (v *NullablePageIndicatorBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageIndicatorBlock(val *PageIndicatorBlock) *NullablePageIndicatorBlock {
	return &NullablePageIndicatorBlock{value: val, isSet: true}
}

func (v NullablePageIndicatorBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageIndicatorBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


