/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// ProgressBarItemContent Progress bar item content
type ProgressBarItemContent struct {
	Title Text `json:"title"`
	Subtitle *Text `json:"subtitle,omitempty"`
	Description *Text `json:"description,omitempty"`
	Image *Image `json:"image,omitempty"`
}

// NewProgressBarItemContent instantiates a new ProgressBarItemContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgressBarItemContent(title Text) *ProgressBarItemContent {
	this := ProgressBarItemContent{}
	this.Title = title
	return &this
}

// NewProgressBarItemContentWithDefaults instantiates a new ProgressBarItemContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgressBarItemContentWithDefaults() *ProgressBarItemContent {
	this := ProgressBarItemContent{}
	return &this
}

// GetTitle returns the Title field value
func (o *ProgressBarItemContent) GetTitle() Text {
	if o == nil {
		var ret Text
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ProgressBarItemContent) GetTitleOk() (*Text, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ProgressBarItemContent) SetTitle(v Text) {
	o.Title = v
}

// GetSubtitle returns the Subtitle field value if set, zero value otherwise.
func (o *ProgressBarItemContent) GetSubtitle() Text {
	if o == nil || isNil(o.Subtitle) {
		var ret Text
		return ret
	}
	return *o.Subtitle
}

// GetSubtitleOk returns a tuple with the Subtitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgressBarItemContent) GetSubtitleOk() (*Text, bool) {
	if o == nil || isNil(o.Subtitle) {
    return nil, false
	}
	return o.Subtitle, true
}

// HasSubtitle returns a boolean if a field has been set.
func (o *ProgressBarItemContent) HasSubtitle() bool {
	if o != nil && !isNil(o.Subtitle) {
		return true
	}

	return false
}

// SetSubtitle gets a reference to the given Text and assigns it to the Subtitle field.
func (o *ProgressBarItemContent) SetSubtitle(v Text) {
	o.Subtitle = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProgressBarItemContent) GetDescription() Text {
	if o == nil || isNil(o.Description) {
		var ret Text
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgressBarItemContent) GetDescriptionOk() (*Text, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProgressBarItemContent) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given Text and assigns it to the Description field.
func (o *ProgressBarItemContent) SetDescription(v Text) {
	o.Description = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *ProgressBarItemContent) GetImage() Image {
	if o == nil || isNil(o.Image) {
		var ret Image
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgressBarItemContent) GetImageOk() (*Image, bool) {
	if o == nil || isNil(o.Image) {
    return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *ProgressBarItemContent) HasImage() bool {
	if o != nil && !isNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given Image and assigns it to the Image field.
func (o *ProgressBarItemContent) SetImage(v Image) {
	o.Image = &v
}

func (o ProgressBarItemContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["title"] = o.Title
	}
	if !isNil(o.Subtitle) {
		toSerialize["subtitle"] = o.Subtitle
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	return json.Marshal(toSerialize)
}

type NullableProgressBarItemContent struct {
	value *ProgressBarItemContent
	isSet bool
}

func (v NullableProgressBarItemContent) Get() *ProgressBarItemContent {
	return v.value
}

func (v *NullableProgressBarItemContent) Set(val *ProgressBarItemContent) {
	v.value = val
	v.isSet = true
}

func (v NullableProgressBarItemContent) IsSet() bool {
	return v.isSet
}

func (v *NullableProgressBarItemContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgressBarItemContent(val *ProgressBarItemContent) *NullableProgressBarItemContent {
	return &NullableProgressBarItemContent{value: val, isSet: true}
}

func (v NullableProgressBarItemContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgressBarItemContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


