package models
// TwoColumnMultipleSelectionListItemType : Combination of fields for two column multiple selection list item
type TwoColumnMultipleSelectionListItemType string

// List of TwoColumnMultipleSelectionListItemType
const (
	TWOCOLUMNMULTIPLESELECTIONLISTITEMTYPE_TITTLE TwoColumnMultipleSelectionListItemType = "Tittle"
	TWOCOLUMNMULTIPLESELECTIONLISTITEMTYPE_TITLE_SUBTITLE TwoColumnMultipleSelectionListItemType = "TitleSubtitle"
	TWOCOLUMNMULTIPLESELECTIONLISTITEMTYPE_SMALL_IMAGE_TITLE TwoColumnMultipleSelectionListItemType = "SmallImageTitle"
	TWOCOLUMNMULTIPLESELECTIONLISTITEMTYPE_MEDIUM_IMAGE_TITLE TwoColumnMultipleSelectionListItemType = "MediumImageTitle"
	TWOCOLUMNMULTIPLESELECTIONLISTITEMTYPE_FULL_IMAGE TwoColumnMultipleSelectionListItemType = "FullImage"
	TWOCOLUMNMULTIPLESELECTIONLISTITEMTYPE_BIG_IMAGE_TITLE TwoColumnMultipleSelectionListItemType = "BigImageTitle"
)
