/*
Onboarding online screens graph models

Onboarding online screens graph models and interfaces

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// ScreenImageTitleSubtitlesAllOf Screen - Image/Title/Subtitles list
type ScreenImageTitleSubtitlesAllOf struct {
	ImageTitleSubtitlesDescription string `json:"imageTitleSubtitlesDescription"`
	Image Image `json:"image"`
	Title Text `json:"title"`
	Subtitle1 Text `json:"subtitle1"`
	Subtitle2 Text `json:"subtitle2"`
}

// NewScreenImageTitleSubtitlesAllOf instantiates a new ScreenImageTitleSubtitlesAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScreenImageTitleSubtitlesAllOf(imageTitleSubtitlesDescription string, image Image, title Text, subtitle1 Text, subtitle2 Text) *ScreenImageTitleSubtitlesAllOf {
	this := ScreenImageTitleSubtitlesAllOf{}
	this.ImageTitleSubtitlesDescription = imageTitleSubtitlesDescription
	this.Image = image
	this.Title = title
	this.Subtitle1 = subtitle1
	this.Subtitle2 = subtitle2
	return &this
}

// NewScreenImageTitleSubtitlesAllOfWithDefaults instantiates a new ScreenImageTitleSubtitlesAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScreenImageTitleSubtitlesAllOfWithDefaults() *ScreenImageTitleSubtitlesAllOf {
	this := ScreenImageTitleSubtitlesAllOf{}
	return &this
}

// GetImageTitleSubtitlesDescription returns the ImageTitleSubtitlesDescription field value
func (o *ScreenImageTitleSubtitlesAllOf) GetImageTitleSubtitlesDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageTitleSubtitlesDescription
}

// GetImageTitleSubtitlesDescriptionOk returns a tuple with the ImageTitleSubtitlesDescription field value
// and a boolean to check if the value has been set.
func (o *ScreenImageTitleSubtitlesAllOf) GetImageTitleSubtitlesDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ImageTitleSubtitlesDescription, true
}

// SetImageTitleSubtitlesDescription sets field value
func (o *ScreenImageTitleSubtitlesAllOf) SetImageTitleSubtitlesDescription(v string) {
	o.ImageTitleSubtitlesDescription = v
}

// GetImage returns the Image field value
func (o *ScreenImageTitleSubtitlesAllOf) GetImage() Image {
	if o == nil {
		var ret Image
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *ScreenImageTitleSubtitlesAllOf) GetImageOk() (*Image, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *ScreenImageTitleSubtitlesAllOf) SetImage(v Image) {
	o.Image = v
}

// GetTitle returns the Title field value
func (o *ScreenImageTitleSubtitlesAllOf) GetTitle() Text {
	if o == nil {
		var ret Text
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ScreenImageTitleSubtitlesAllOf) GetTitleOk() (*Text, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ScreenImageTitleSubtitlesAllOf) SetTitle(v Text) {
	o.Title = v
}

// GetSubtitle1 returns the Subtitle1 field value
func (o *ScreenImageTitleSubtitlesAllOf) GetSubtitle1() Text {
	if o == nil {
		var ret Text
		return ret
	}

	return o.Subtitle1
}

// GetSubtitle1Ok returns a tuple with the Subtitle1 field value
// and a boolean to check if the value has been set.
func (o *ScreenImageTitleSubtitlesAllOf) GetSubtitle1Ok() (*Text, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Subtitle1, true
}

// SetSubtitle1 sets field value
func (o *ScreenImageTitleSubtitlesAllOf) SetSubtitle1(v Text) {
	o.Subtitle1 = v
}

// GetSubtitle2 returns the Subtitle2 field value
func (o *ScreenImageTitleSubtitlesAllOf) GetSubtitle2() Text {
	if o == nil {
		var ret Text
		return ret
	}

	return o.Subtitle2
}

// GetSubtitle2Ok returns a tuple with the Subtitle2 field value
// and a boolean to check if the value has been set.
func (o *ScreenImageTitleSubtitlesAllOf) GetSubtitle2Ok() (*Text, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Subtitle2, true
}

// SetSubtitle2 sets field value
func (o *ScreenImageTitleSubtitlesAllOf) SetSubtitle2(v Text) {
	o.Subtitle2 = v
}

func (o ScreenImageTitleSubtitlesAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["imageTitleSubtitlesDescription"] = o.ImageTitleSubtitlesDescription
	}
	if true {
		toSerialize["image"] = o.Image
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["subtitle1"] = o.Subtitle1
	}
	if true {
		toSerialize["subtitle2"] = o.Subtitle2
	}
	return json.Marshal(toSerialize)
}

type NullableScreenImageTitleSubtitlesAllOf struct {
	value *ScreenImageTitleSubtitlesAllOf
	isSet bool
}

func (v NullableScreenImageTitleSubtitlesAllOf) Get() *ScreenImageTitleSubtitlesAllOf {
	return v.value
}

func (v *NullableScreenImageTitleSubtitlesAllOf) Set(val *ScreenImageTitleSubtitlesAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableScreenImageTitleSubtitlesAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableScreenImageTitleSubtitlesAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScreenImageTitleSubtitlesAllOf(val *ScreenImageTitleSubtitlesAllOf) *NullableScreenImageTitleSubtitlesAllOf {
	return &NullableScreenImageTitleSubtitlesAllOf{value: val, isSet: true}
}

func (v NullableScreenImageTitleSubtitlesAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScreenImageTitleSubtitlesAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


